### PR TITLE
Add registration and login pages

### PR DESCRIPTION
**Pull request by Burugux**
Adds a registration page with a form and login page with a form.
* Registration page
image

* Login page
image

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
- The designs are simple and atomic. Keep up the work.

**Comment by kenyanerd** [comment]
Nice work on the design @burugux

**Comment by Xerrex** [comment]
Nice. But instead of Two password field labels change the last one to be `Confirm password`.

**Comment by Nerldy** [comment]
You can never go wrong with simplicity. Good job.

**Comment by Burugux** [comment]
@Xerrex thank you for your review! I have removed that duplication in this commit 4caf83aa9bb06473e9e8158ba8032fa6f809d29e

**Comment by oagutu** [comment]
Good use of minimalism. Not sure if it's been cut out in the screenshots, but I think the app name(i.e. hello books) should appear somewhere in the login/signup pages, just as a UX formality.

**Comment by Burugux** [comment]
@oagutu I had not included it yet but i have fixed that as of this commit 3e2244ee6dfaec196766e661bc846b05a16c9c0b
* Sign up
image
* Login
image

**Comment by faustineomuya** [comment]
Simple and  creative. Really nice.

**Pull request merged**
